### ISSUE TITLE
Unable to access UI from remote machine

### ISSUE THREAD

**Issue by kazaker** [OpenCSPM/opencspm#103]
Hello guys. 
I'm trying to launch OpenCSPM in local mode on my Linux virtual machine. It looks like an applications starts correctly, but when I try to access Web UI from web browser on my personal computer I get the following error:

Blocked host: **<IP of VM on witch OpenCSPM is running>**
To allow requests to **<IP of VM on witch OpenCSPM is running>**, add the following to your environment configuration:
config.hosts << "**<IP of VM on witch OpenCSPM is running>**"

Unfortunately I was unable to find instructions on how to fix this. General googling suggested to add line "config.hosts << "**<IP of VM on witch OpenCSPM is running>**"" to the file opencspm-demo/opencspm/docker/config/environments/development.rb, but it doesn't seem help.

If you advise on how to fix this I would appreciate it.

**Comment by joshlarsen** [comment]
Hi @kazaker, remote access isn't supported yet. But you can try it out by modifying the `ui_host` and `cookie_domain` settings in the [custom.rb](https://github.com/OpenCSPM/opencspm/blob/main/docker/config/initializers/custom.rb#L25-L46) initializer.

**Comment by kazaker** [comment]
Hello @joshlarsen, thank you for your help, I'll try it.

**Comment by sathish-ather** [comment]
Hey Guys,

Seems the issue not fixed. We as well getting the same error while try to access the web UI from remote machine.

we tried the above suggestions, but it doesn't helped.

Could you help us to fix this issue !
<img width="953" alt="Screenshot 2021-08-06 at 11 30 36 AM" src="https://user-images.githubusercontent.com/81147114/128463439-459f2e90-5221-4fce-8e3a-a280e2380f65.png">
