### ISSUE TITLE
opencspm install question

### ISSUE THREAD

**Issue by niuzhi** [OpenCSPM/opencspm#142]
Hello, I installed opencspm through the introductory guide. The console information is as follows, and the web browser cannot be accessed. What is the problem?
![image](https://user-images.githubusercontent.com/33443724/112824911-a6931900-907a-11eb-9177-60e7e1b17d8f.png)

**Comment by joshlarsen** [comment]
Please use an [issue template](https://github.com/OpenCSPM/opencspm/issues/new/choose) when opening an issue.
