### ISSUE TITLE
opencspm install question

### ISSUE THREAD

**Issue by niuzhi** [OpenCSPM/opencspm#143]
Hello, I installed opencspm through the introductory guide. The console information is as follows, and the web browser cannot be accessed. What is the problem?
![image](https://user-images.githubusercontent.com/33443724/112841817-7b1b2900-9090-11eb-8a6e-64285b2a8f6c.png)

**Comment by joshlarsen** [comment]
Please use an [issue template](https://github.com/OpenCSPM/opencspm/issues/new/choose) when opening an issue.
