### ISSUE TITLE
OpenCSPM UI Not Reflecting Config.yaml Changes Without Restarting

### ISSUE THREAD

**Issue by christophetd** [OpenCSPM/opencspm#16]
**Describe the bug**

Having followed instructions at https://github.com/OpenCSPM/opencspm/blob/main/site/data_collection.md#aws-cloud-resources, OpenCSPM does not pick up my custom data.

```
# ls -l assets/custom
total 316
-rw-r--r-- 1 christophetd christophetd     12 nov.  16 12:35 manifest.txt
-rwxr-xr-x 1 christophetd christophetd 316195 nov.  16 12:35 output.json

$ cat assets/custom/manifest.txt
output.json

$ cat config/config.yaml
---
db:
  host: redis
  port: 6379
buckets:
  # - gs://darkbit-collection-us-cspm
  # - s3://my-other-bucket-here
local_dirs:
  - /app/data/custom
  # - /app/data/test
```

I did run `docker-compose down && docker-compose up` after making these modifications.

No visible error in logs

**Expected behavior**

OpenCSPM should pick up the new resources file

**Screenshots**

UI:

![image](https://user-images.githubusercontent.com/136675/99248739-38effa00-2809-11eb-8abb-e9495bd3cd02.png)

**Docker information (please complete the following information):**

```
$ docker --version
Docker version 19.03.13, build 4484c46d9d

$ docker-compose --version
docker-compose version 1.27.4, build 40524192
```

**Cloud provider (if applicable):**

AWS

**Comment by christophetd** [comment]
Solved: I had to manually delete Docker volumes (`docker volume rm opencspm_core opencspm_postgres opencspm_redis`) and restart OpenCSPM. Might be worth mentioning in the docs

**Comment by joshlarsen** [comment]
This is a UI bug. The new files will be loaded since the `config.yaml` is re-read every time the background job runs, but it is not reflected correctly in the UI.
