### ISSUE TITLE
Dashboard Status Inactive and Controls Missing

### ISSUE THREAD

**Issue by SurhanZahid** [OpenCSPM/opencspm#174]
**Describe the bug**
i have tried to use your tool but when i open the dashboard it gives me inactive and doesn't show data even from the demo you provided. I followed all of the steps in the guide with aws-recon and aws-vault and got the data in a json file and configured the config.yaml file and the cli shows the worker service showing that the job was successfully done.

**Expected behavior**
The profile section should be active instead of inactive and the controls should be displayed 

**Screenshots**
![Screenshot from 2021-05-27 22-42-33](https://user-images.githubusercontent.com/32094006/119872475-f5571500-bf3c-11eb-945e-9370bc7ffa4c.png)
![Screenshot from 2021-05-27 22-42-48](https://user-images.githubusercontent.com/32094006/119872494-f8520580-bf3c-11eb-83cc-2a0c6e00d6d5.png)

**Cloud provider (if applicable):**
i am using aws cloud

**Comment by joshlarsen** [comment]
There are no controls, or they are in the wrong directory. This is the cause of the `No examples found` log message.

From location where you cloned the repo, please share the output of:

```
find . -type d -maxdepth 2
```

**Comment by SurhanZahid** [comment]
ok this is the output 
![Screenshot from 2021-05-28 01-56-35](https://user-images.githubusercontent.com/32094006/119896120-02353200-bf58-11eb-85d3-33a4025e98a9.png)

**Comment by joshlarsen** [comment]
Ok, and how about:

```
find ../opencspm-controls -type d -maxdepth 2
```

**Comment by SurhanZahid** [comment]
This is the output

![Screenshot from 2021-05-28 11-36-57](https://user-images.githubusercontent.com/32094006/119940729-0b9aba80-bfa9-11eb-8558-892921c5a03d.png)

**Comment by joshlarsen** [comment]
There are no control packs there, so OpenCSPM has nothing to load or analyze. Please double check the portion of the instructions that explain how to download the control packs.

**Comment by SurhanZahid** [comment]
ok i followed the the entire instructions again now the worker_1 is giving back this error 

![Screenshot from 2021-05-28 16-42-32](https://user-images.githubusercontent.com/32094006/119979050-d8215580-bfd3-11eb-838a-fcfccdd89c06.png)

**Comment by joshlarsen** [comment]
Please remove the old volumes and restart. E.g.:

```
docker-compose down -v
```

then

```
docker-compose up
```
