### ISSUE TITLE
all hosts blocked except localhost on Rails

### ISSUE THREAD

**Issue by VinniMarcon** [OpenCSPM/opencspm#186]
**Describe the bug**
I'm trying to use the application inside a GCP Ubuntu VM, applying it to the local IP address and then using IP forwading to redirect external traffic to it

The problem is that, doing the test both in GCP and locally, the problem is always the same, I can't get the application to work with the local IP address instead of localhost because apparently Rails blocks any hosts other than localhost, as shown in the screenshot.

I've tried numerous ways to solve this problem, following some tips on [stackoverflow](https://stackoverflow.com/questions/53878453/upgraded-rails-to-6-getting-blocked-host-error) and some tips in [this issue](https://github.com/OpenCSPM/opencspm/issues/103), such as:

1. in the `config/initializers/custom.rb` file, I tried to add the lines `config.hosts.clear`, `config.hosts << "192.168.0.14"`, `config.hosts << "my_hostname_name"`

2. in the `config/enviroments/development.rb` file, I tried to change the `ui_host` and `cookie_domain` lines to my hostname and local IP address

3. in the `config/application.rb` file, I tried to add the `Rails.application.config.hosts.clear` line to release all hosts

i also asked the firewall to accept all necessary ports like 5000, 8000 and 5432, just in case

and after each change, I reinstalled the entire application using `docker-compose down -v` and `docker-compose up`, but none of the alternatives, and in none of the environments did it solve the problem.

is there any way I can solve this? access my application via `http://my_local_ip:5000` instead of `http://localhost:5000`?

**OpenCSPM version**
0.1.23

**Expected behavior**
access the application via my local ip address instead of localhost, to establish access for other addresses on the network (ex: http://192.168.0.14:5000)

**Screenshots**
![imagem](https://user-images.githubusercontent.com/42422427/128556317-05bad1d4-5c42-45a6-8cef-0cc382000aab.png)

**Docker information**
20.10.2
docker-compose: 1.26.0

**Cloud provider**
GCP

**Comment by sathish-ather** [comment]
Yup.. Facing the same issue.

**Comment by joshlarsen** [comment]
This is by design. Accessing the web ui over the network is not possible the way the Docker image is currently built.

The frontend (vue.js) app is bundled and built into the Docker image. There is no SSL/TLS certificate support and the location of backend (Rails API) is hardcoded into the frontend ui bundle.
