### ISSUE TITLE
Docker deployment setup of opencspm on non-localhost endpoint

### ISSUE THREAD

**Issue by sprathod369** [OpenCSPM/opencspm#192]
I tried deploying the opencspm application using docker-compose on my test VM (Ubuntu), the application doesn't get deployed on a VM. The same docker-compose works on my local laptop and accessible at **localhost:5000** end point.

Spend some time on the source code and it looks like the localhost url is hardcoded in their source code. Tried changing the url in their source code but it didn't work and also tried the configuration of IP Address in the environment configuration as suggested in below error, but the application is still not accessible on the IP Address of a VM. 
Any inputs / suggestion will be appreciated
Error:
![image](https://user-images.githubusercontent.com/73107830/146120756-bd85da20-a549-4593-98f4-4bc595891fb6.png)

**Comment by joshlarsen** [comment]
Hi @sprathod369, this is by design. Take a look at #186 for more explanation.
