### ISSUE TITLE
Error: services.core.depends_on contains an invalid type, it should be an array

### ISSUE THREAD

**Issue by coffeewithayman** [OpenCSPM/opencspm#25]
Getting the following error when doing a `docker-compose up`:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.core.depends_on contains an invalid type, it should be an array
services.worker.depends_on contains an invalid type, it should be an array
```

Taking a deeper look, it seems related to Version 3 of docker no longer supporting the condition form of `depends_on`.

From: https://docs.docker.com/compose/compose-file/
```
There are several things to be aware of when using depends_on:

- depends_on does not wait for db and redis to be “ready” before starting web - only until they have been started. If you need to wait for a service to be ready, see Controlling startup order for more on this problem and strategies for solving it.
- Version 3 no longer supports the condition form of depends_on.
- The depends_on option is ignored when deploying a stack in swarm mode with a version 3 Compose file.
```

**To Reproduce**
`docker-compose up`

**Docker information (please complete the following information):**
Docker version 19.03.6, build 369ce74a3c
docker-compose version 1.25.5, build 8a1c60f6

**Additional context**
Not really sure how others are not getting this error since this has been in there for 2 months, so not sure what I'm doing wrong. Removing `depends_on` does get docker-compose to start, but had to run twice. :) Searched to see if this existed before and didn't see, but forgive me if I'm missing something. Others getting this error?

**Fix**
Removed `condition` and changed to arrays:
```    
depends_on:
      - core
      - db
      - redis
```

```
depends_on:
      - db
      - redis
```
I can put an PR for this if you like. Lmk.

**Comment by joshlarsen** [comment]
Thanks @coffeewithayman. This is strange, as we use this daily without issue. Can you please post the full output from `docker version`?

**Comment by coffeewithayman** [comment]
Yeah, my thoughts as well. Here is the full output of `docker version`:

```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Wed Oct 14 19:00:27 2020
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by joshlarsen** [comment]
Removed the conditions from `depends_on` in https://github.com/OpenCSPM/opencspm/commit/b72635ed1ac6ddbb87760e41f8e39cfbc6ee3df1.

Please test the latest `docker-compose.yml` with:

```
docker-compose down -v
```

then

```
docker-compose up
```


Let me know if everything comes up clean.

**Comment by coffeewithayman** [comment]
@joshlarsen worked smoothly, thanks!
